# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'abc', max_length=80)),
                ('last_name', models.CharField(default=b'abc', max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(upload_to=profiles.models.upload_location)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'N', b'Not Disclosed')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'abc', max_length=80)),
                ('last_name', models.CharField(default=b'abc', max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(upload_to=profiles.models.upload_location)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'N', b'Not Disclosed')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
