# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_participantprofile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location),
        ),
    ]
